"""
create_genie.py — Genie Space Configuration
=============================================
Stores the Genie Space config as code and can update an existing space's
title, description, and warehouse via the Databricks SDK.

First-time creation:
  The Databricks SDK requires an internal 'serialized_space' field that is
  only generated by the Databricks UI. To create the space for the first time:
    1. Open: https://adb-6417907769725610.10.azuredatabricks.net
    2. Go to Genie → New Genie Space
    3. Name it "Financial Reports Analytics"
    4. Add tables: unstructured.rag_data.fin_kpis
                   unstructured.rag_data.fin_audit_findings
    5. Set warehouse to: 2f0c6e5a9e9d67d1
    6. Save the space_id to genie_info.json or pass it via --space-id

Updating an existing space:
    python3.11 create_genie.py --space-id <space_id>

Environment:
    DATABRICKS_HOST   Workspace URL (or ~/.databrickscfg)
    DATABRICKS_TOKEN  Personal access token (or ~/.databrickscfg)
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

HOST         = "https://adb-6417907769725610.10.azuredatabricks.net"
WAREHOUSE_ID = "2f0c6e5a9e9d67d1"
CATALOG      = "unstructured"
SCHEMA       = "rag_data"

DISPLAY_NAME = "Financial Reports Analytics"

TABLES = [
    f"{CATALOG}.{SCHEMA}.fin_kpis",
    f"{CATALOG}.{SCHEMA}.fin_audit_findings",
]

DESCRIPTION = """Explore structured financial KPIs and audit findings extracted from 20 corporate financial documents covering Q1–Q4 2025 and FY2026 forecasts.

Tables:
- fin_kpis: Numeric KPIs per document (doc_id, title, doc_type, period, metric_name, metric_value, metric_unit, notes).
  doc_type values: earnings, budget, policy, audit, forecast, tax, risk, esg, m_and_a, debt, operations, hr.
  96 rows across 20 documents.
- fin_audit_findings: Control findings from internal audit and SOX reports
  (doc_id, title, finding_name, risk_rating, remediation_days, status).
  risk_rating values: High, Medium, Low, Material Weakness, Significant Deficiency, Control Deficiency.
  10 rows.

Join key: doc_id links both tables."""

SAMPLE_QUESTIONS = [
    "What was the total revenue in Q1, Q2, Q3, and Q4 2025?",
    "Which quarter had the highest revenue growth?",
    "Show me all High risk audit findings and their remediation timelines",
    "What is the total FY2026 budget across all departments?",
    "Compare Scope 1 and Scope 2 emissions reductions from the ESG report",
    "What are the CapEx approval thresholds by tier?",
    "Which documents have the most KPIs extracted?",
    "Show all metrics from the M&A due diligence report",
    "What is the interest coverage ratio from the debt report?",
    "How many audit findings are still Open vs In Progress?",
    "What is the bonus pool percentage from the compensation report?",
    "Show all earnings metrics sorted by period",
]

GENIE_INFO_PATH = Path(__file__).parent / "genie_info.json"

try:
    from databricks.sdk import WorkspaceClient
except ImportError:
    print("ERROR: pip install databricks-sdk>=0.20.0")
    sys.exit(1)


def load_space_id(arg_space_id: str | None) -> str | None:
    if arg_space_id:
        return arg_space_id
    if GENIE_INFO_PATH.exists():
        return json.loads(GENIE_INFO_PATH.read_text()).get("space_id")
    return None


def save_info(space_id: str) -> None:
    GENIE_INFO_PATH.write_text(json.dumps({
        "space_id":      space_id,
        "display_name":  DISPLAY_NAME,
        "tables":        TABLES,
        "warehouse_id":  WAREHOUSE_ID,
        "workspace_url": HOST,
        "url":           f"{HOST}/genie/rooms/{space_id}",
    }, indent=2))


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Configure the Financial Reports Genie Space.")
    p.add_argument("--space-id", default=None,
                   help="Space ID to update (falls back to genie_info.json if omitted)")
    return p.parse_args()


def main() -> None:
    args = parse_args()

    print("Connecting to Databricks…")
    client = WorkspaceClient(host=HOST)
    print(f"Connected as {client.current_user.me().user_name}\n")

    space_id = load_space_id(args.space_id)

    if space_id:
        # Update existing space
        print(f"Updating Genie Space {space_id}…")
        client.genie.update_space(
            space_id=space_id,
            title=DISPLAY_NAME,
            description=DESCRIPTION,
            warehouse_id=WAREHOUSE_ID,
        )
        save_info(space_id)
        print(f"\n✓ Genie Space updated")
    else:
        # No space_id — print creation instructions
        print("No existing space_id found.\n")
        print("To create the Genie Space for the first time:")
        print(f"  1. Open: {HOST}")
        print("  2. Go to Genie → New Genie Space")
        print(f"  3. Name it: {DISPLAY_NAME}")
        print("  4. Add tables:")
        for t in TABLES:
            print(f"       {t}")
        print(f"  5. Set warehouse: {WAREHOUSE_ID}")
        print("  6. Click Create, then re-run with the space_id:")
        print("       python3.11 create_genie.py --space-id <space_id>")
        print("\nThe space_id appears in the URL:")
        print("  https://<workspace>/genie/rooms/<space_id>")
        sys.exit(0)

    print(f"  Name     : {DISPLAY_NAME}")
    print(f"  Space ID : {space_id}")
    print(f"  Tables   : {', '.join(TABLES)}")
    print(f"  URL      : {HOST}/genie/rooms/{space_id}")
    print(f"  Config   : genie_info.json")


if __name__ == "__main__":
    main()
