"""
RAG Evaluation Harness — Financial Reports Assistant
=====================================================
Loads the 20 companion eval JSON files produced by generate_pdfs.py, queries
the Financial Reports Assistant Knowledge Assistant endpoint for each question,
scores each answer against its human-written guideline using an LLM-as-judge,
and writes a full results file plus a printed summary table.

Usage:
    python evaluate_rag.py [--eval-dir PATH] [--results-dir PATH] [--verbose]

Environment:
    DATABRICKS_HOST   Workspace URL  (or set in ~/.databrickscfg)
    DATABRICKS_TOKEN  Personal access token (or set in ~/.databrickscfg)
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

HOST          = "https://adb-6417907769725610.10.azuredatabricks.net"
ENDPOINT_NAME = "ka-e53ea1a5-endpoint"

# Path to the companion JSON files generated by generate_pdfs.py
DEFAULT_EVAL_DIR    = Path(__file__).parent.parent / "pdf-gen-rag" / "output"
DEFAULT_RESULTS_DIR = Path(__file__).parent / "results"

# Model used to judge answer quality (must be available on the workspace)
JUDGE_MODEL = "databricks-meta-llama-3-3-70b-instruct"

JUDGE_PROMPT_TEMPLATE = """\
You are an expert evaluator assessing the quality of an AI assistant's answer.

Question: {question}

Guideline (what a correct answer must include):
{guideline}

Assistant answer:
{answer}

Evaluate whether the assistant's answer satisfies the guideline.
Respond with a JSON object with exactly these fields:
{{
  "score": <0 or 1>,
  "reasoning": "<one or two sentences explaining your decision>"
}}

Score 1 if the answer substantially satisfies the guideline.
Score 0 if it is missing key required information or is factually wrong.
Return only valid JSON, no markdown fences."""

# ---------------------------------------------------------------------------
# Imports (deferred to give a clean error if SDK is missing)
# ---------------------------------------------------------------------------

try:
    from databricks.sdk import WorkspaceClient
    from databricks.sdk.service.serving import ChatMessage, ChatMessageRole
except ImportError:
    print("ERROR: databricks-sdk is not installed. Run: pip install databricks-sdk>=0.20.0")
    sys.exit(1)

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def load_eval_cases(eval_dir: Path) -> list[dict[str, Any]]:
    """Load all fin_report_*.json files from eval_dir and return as a list."""
    paths = sorted(eval_dir.glob("fin_report_*.json"))
    if not paths:
        raise FileNotFoundError(
            f"No fin_report_*.json files found in {eval_dir}.\n"
            "Run generate_pdfs.py first, or set --eval-dir to the correct path."
        )
    cases = []
    for p in paths:
        with open(p) as f:
            cases.append(json.load(f))
    print(f"Loaded {len(cases)} evaluation cases from {eval_dir}")
    return cases


def query_knowledge_assistant(
    client: WorkspaceClient,
    question: str,
    endpoint_name: str = ENDPOINT_NAME,
    retries: int = 3,
) -> tuple[str, list[str]]:
    """
    Query the Knowledge Assistant endpoint.

    Returns:
        (answer_text, list_of_source_citations)
    """
    for attempt in range(1, retries + 1):
        try:
            resp = client.api_client.do(
                "POST",
                f"/serving-endpoints/{endpoint_name}/invocations",
                body={"input": [{"role": "user", "content": question}]},
            )

            # Parse OpenAI Responses API format returned by Agent Bricks KA
            answer_parts: list[str] = []
            citations: list[str] = []
            for msg in resp.get("output", []):
                for part in msg.get("content", []):
                    if part.get("type") == "output_text":
                        answer_parts.append(part.get("text", ""))
                        for ann in part.get("annotations", []):
                            title = ann.get("title", "")
                            if title and title not in citations:
                                citations.append(title)

            return "".join(answer_parts), citations

        except Exception as exc:
            if attempt == retries:
                raise
            wait = 2 ** attempt
            print(f"    Attempt {attempt} failed ({exc}). Retrying in {wait}s…")
            time.sleep(wait)

    return "", []


def judge_answer(
    client: WorkspaceClient,
    question: str,
    guideline: str,
    answer: str,
) -> dict[str, Any]:
    """
    Use an LLM-as-judge to score whether `answer` satisfies `guideline`.

    Returns a dict with keys: score (0 or 1), reasoning (str)
    """
    prompt = JUDGE_PROMPT_TEMPLATE.format(
        question=question,
        guideline=guideline,
        answer=answer,
    )
    response = client.serving_endpoints.query(
        name=JUDGE_MODEL,
        messages=[ChatMessage(role=ChatMessageRole.USER, content=prompt)],
        max_tokens=256,
        temperature=0.0,
    )
    raw = response.choices[0].message.content.strip()

    # Strip markdown fences if model wraps response
    if raw.startswith("```"):
        raw = raw.split("```")[1]
        if raw.startswith("json"):
            raw = raw[4:]
        raw = raw.strip()

    try:
        result = json.loads(raw)
        return {
            "score":     int(result.get("score", 0)),
            "reasoning": str(result.get("reasoning", "")),
        }
    except (json.JSONDecodeError, ValueError):
        # Fallback: attempt to extract score from raw text
        score = 1 if '"score": 1' in raw or "'score': 1" in raw else 0
        return {"score": score, "reasoning": raw[:200]}


def print_summary_table(results: list[dict[str, Any]]) -> None:
    """Print a formatted results table to stdout."""
    col_widths = [4, 40, 7, 60]
    header = f"{'#':<{col_widths[0]}}  {'Document':<{col_widths[1]}}  {'Score':<{col_widths[2]}}  {'Reasoning':<{col_widths[3]}}"
    separator = "-" * (sum(col_widths) + 6)

    print("\n" + separator)
    print(header)
    print(separator)

    for r in results:
        score_str = "PASS" if r["score"] == 1 else "FAIL"
        title = r["title"][:38] + ".." if len(r["title"]) > 40 else r["title"]
        reasoning = r["reasoning"][:58] + ".." if len(r["reasoning"]) > 60 else r["reasoning"]
        print(f"{r['index']:<{col_widths[0]}}  {title:<{col_widths[1]}}  {score_str:<{col_widths[2]}}  {reasoning}")

    total   = len(results)
    passed  = sum(1 for r in results if r["score"] == 1)
    failed  = total - passed
    pct     = (passed / total * 100) if total else 0

    print(separator)
    print(f"\nResults: {passed}/{total} PASS ({pct:.1f}%)   |   {failed} FAIL")
    print()


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Evaluate the Financial Reports Knowledge Assistant against 20 ground-truth questions."
    )
    parser.add_argument(
        "--eval-dir",
        type=Path,
        default=DEFAULT_EVAL_DIR,
        help=f"Directory containing fin_report_*.json eval files (default: {DEFAULT_EVAL_DIR})",
    )
    parser.add_argument(
        "--results-dir",
        type=Path,
        default=DEFAULT_RESULTS_DIR,
        help=f"Directory to write eval_results.json (default: {DEFAULT_RESULTS_DIR})",
    )
    parser.add_argument(
        "--endpoint",
        default=ENDPOINT_NAME,
        help=f"Knowledge Assistant endpoint name (default: {ENDPOINT_NAME})",
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Print full answers and reasoning for each question",
    )
    parser.add_argument(
        "--no-judge",
        action="store_true",
        help="Skip LLM judge scoring (record answers only)",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()

    print("=" * 60)
    print("Financial Reports Assistant — RAG Evaluation")
    print("=" * 60)
    print(f"Host         : {HOST}")
    print(f"Endpoint     : {args.endpoint}")
    print(f"Eval dir     : {args.eval_dir}")
    print(f"Results dir  : {args.results_dir}")
    print()

    # Connect
    print("Connecting to Databricks workspace…")
    client = WorkspaceClient(host=HOST)
    print("Connected.\n")

    # Load eval cases
    eval_cases = load_eval_cases(args.eval_dir)

    # Create results directory
    args.results_dir.mkdir(parents=True, exist_ok=True)

    results: list[dict[str, Any]] = []
    errors:  list[str]            = []

    for i, case in enumerate(eval_cases, start=1):
        title     = case.get("title", f"Document {i}")
        question  = case.get("question", "")
        guideline = case.get("guideline", "")
        pdf_path  = case.get("pdf_path", "")

        print(f"[{i:02d}/{len(eval_cases)}] {title}")
        print(f"         Q: {question}")

        # 1. Query the Knowledge Assistant
        try:
            answer, citations = query_knowledge_assistant(client, question, args.endpoint)
        except Exception as exc:
            err_msg = f"Query failed: {exc}"
            print(f"         ERROR: {err_msg}\n")
            errors.append(f"Case {i} ({title}): {err_msg}")
            results.append({
                "index":     i,
                "title":     title,
                "question":  question,
                "guideline": guideline,
                "pdf_path":  pdf_path,
                "answer":    "",
                "citations": [],
                "score":     0,
                "reasoning": err_msg,
                "error":     True,
            })
            continue

        if args.verbose:
            print(f"         A: {answer[:300]}{'…' if len(answer) > 300 else ''}")

        # 2. Score with LLM judge (unless suppressed)
        score, reasoning = 0, "Scoring skipped (--no-judge)"
        if not args.no_judge and question and guideline:
            try:
                judgment  = judge_answer(client, question, guideline, answer)
                score     = judgment["score"]
                reasoning = judgment["reasoning"]
            except Exception as exc:
                reasoning = f"Judge failed: {exc}"
                errors.append(f"Case {i} ({title}): judge error — {exc}")

        verdict = "PASS" if score == 1 else "FAIL"
        print(f"         Result: {verdict}  |  {reasoning[:80]}{'…' if len(reasoning) > 80 else ''}\n")

        results.append({
            "index":     i,
            "title":     title,
            "question":  question,
            "guideline": guideline,
            "pdf_path":  pdf_path,
            "answer":    answer,
            "citations": citations,
            "score":     score,
            "reasoning": reasoning,
            "error":     False,
        })

    # Summary table
    print_summary_table(results)

    # Write results file
    output = {
        "run_timestamp": datetime.now(timezone.utc).isoformat(),
        "host":          HOST,
        "endpoint":      args.endpoint,
        "total":         len(results),
        "passed":        sum(1 for r in results if r["score"] == 1),
        "failed":        sum(1 for r in results if r["score"] == 0),
        "errors":        errors,
        "results":       results,
    }
    out_path = args.results_dir / "eval_results.json"
    with open(out_path, "w") as f:
        json.dump(output, f, indent=2)
    print(f"Full results written to: {out_path}")

    # Exit with non-zero if more than half failed (useful in CI)
    pass_rate = output["passed"] / output["total"] if output["total"] else 0
    if pass_rate < 0.5:
        print(f"\nWARNING: Pass rate {pass_rate:.0%} is below 50%. Check endpoint and document indexing.")
        sys.exit(1)


if __name__ == "__main__":
    main()
